### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by H8to** [mdifferding/amazon-expense-crawler#1]
Hey!
The script is great, however it stopped working (last used it 2016 or so :D).
It seems the login does still work, but https://www.amazon.de/gp/css/order-history/ref=oh_aui_pagination_3_1?ie=UTF8&orderFilter=year-2018 eg. does again load the login form. 
Maybe there is an issue with the cookie storage?

Regards,
H8

**Comment by mdifferding** [comment]
Hey,

A couple of weeks ago, I also tried the script to parse my shopping information from 2018 and noticed the same issues. About a year ago, it still worked, but amazon might have made some changes to the login system in the meantime.
I've tried a couple of things, but unfortunately couldn't get it to work again. I also played around with a script using BeautifulSoup and requests, but that didn't work either. It seems that all the popular login strategies are outdated.

You could take a look yourself and help, if you want to. I'm not a professional programmer and have little experience with http requests. 

Liebe Grüße (best regards),

M

**Comment by mdifferding** [comment]
Hey,

A couple of weeks ago, I also tried the script to parse my shopping information from 2018 and noticed the same issues. About a year ago, it still worked, but amazon might have made some changes to the login system in the meantime.
I've tried a couple of things, but unfortunately couldn't get it to work again. I also played around with a script using BeautifulSoup and requests, but that didn't work either. It seems that all the popular login strategies are outdated.

You could take a look yourself and help, if you want to. I'm not a professional programmer and have little experience with http requests. 

Liebe Grüße (best regards),

M
